# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/uri/Programs/Bavel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/uri/Programs/Bavel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uri/Programs/Bavel/CMakeFiles /home/uri/Programs/Bavel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uri/Programs/Bavel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bavel

# Build rule for target.
bavel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bavel
.PHONY : bavel

# fast build rule for target.
bavel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/build
.PHONY : bavel/fast

src/DirectoryReader.o: src/DirectoryReader.cpp.o
.PHONY : src/DirectoryReader.o

# target to build an object file
src/DirectoryReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/DirectoryReader.cpp.o
.PHONY : src/DirectoryReader.cpp.o

src/DirectoryReader.i: src/DirectoryReader.cpp.i
.PHONY : src/DirectoryReader.i

# target to preprocess a source file
src/DirectoryReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/DirectoryReader.cpp.i
.PHONY : src/DirectoryReader.cpp.i

src/DirectoryReader.s: src/DirectoryReader.cpp.s
.PHONY : src/DirectoryReader.s

# target to generate assembly for a file
src/DirectoryReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/DirectoryReader.cpp.s
.PHONY : src/DirectoryReader.cpp.s

src/ListItem.o: src/ListItem.cpp.o
.PHONY : src/ListItem.o

# target to build an object file
src/ListItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ListItem.cpp.o
.PHONY : src/ListItem.cpp.o

src/ListItem.i: src/ListItem.cpp.i
.PHONY : src/ListItem.i

# target to preprocess a source file
src/ListItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ListItem.cpp.i
.PHONY : src/ListItem.cpp.i

src/ListItem.s: src/ListItem.cpp.s
.PHONY : src/ListItem.s

# target to generate assembly for a file
src/ListItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ListItem.cpp.s
.PHONY : src/ListItem.cpp.s

src/ProcessingFuncs.o: src/ProcessingFuncs.cpp.o
.PHONY : src/ProcessingFuncs.o

# target to build an object file
src/ProcessingFuncs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ProcessingFuncs.cpp.o
.PHONY : src/ProcessingFuncs.cpp.o

src/ProcessingFuncs.i: src/ProcessingFuncs.cpp.i
.PHONY : src/ProcessingFuncs.i

# target to preprocess a source file
src/ProcessingFuncs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ProcessingFuncs.cpp.i
.PHONY : src/ProcessingFuncs.cpp.i

src/ProcessingFuncs.s: src/ProcessingFuncs.cpp.s
.PHONY : src/ProcessingFuncs.s

# target to generate assembly for a file
src/ProcessingFuncs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/ProcessingFuncs.cpp.s
.PHONY : src/ProcessingFuncs.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bavel.dir/build.make CMakeFiles/bavel.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bavel"
	@echo "... src/DirectoryReader.o"
	@echo "... src/DirectoryReader.i"
	@echo "... src/DirectoryReader.s"
	@echo "... src/ListItem.o"
	@echo "... src/ListItem.i"
	@echo "... src/ListItem.s"
	@echo "... src/ProcessingFuncs.o"
	@echo "... src/ProcessingFuncs.i"
	@echo "... src/ProcessingFuncs.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

